version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_agent:/home/jenkins/agent
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  agent:
    build:
      context: ./jenkins_agent
    container_name: jenkins-agent
    volumes:
      - ./PlaywrightJSJan2025:/workspace
    working_dir: /workspace
    command: tail -f /dev/null

volumes:
  jenkins_home:
